In [1]:
import pandas as pd

### 1. Company Data

In [2]:
data = pd.read_csv("D:/Top mentor/Machine learning/Machine learning assinments/Random Forests - Assignment -5/10. Random Forests/Company_Data.csv")
data.head(5)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No

In [3]:
data.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [4]:
data['ShelveLoc'].unique()

array(['Bad', 'Good', 'Medium'], dtype=object)

In [5]:
data['ShelveLoc'] = data['ShelveLoc'].map({'Bad':0, 'Good':1, 'Medium':2})
data

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,0,42,17,Yes,Yes
1,11.22,111,48,16,260,83,1,65,10,Yes,Yes
2,10.06,113,35,10,269,80,2,59,12,Yes,Yes
3,7.40,117,100,4,466,97,2,55,14,Yes,Yes
4,4.15,141,64,3,340,128,0,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,1,33,14,Yes,Yes
396,6.14,139,23,3,37,120,2,55,11,No,Yes
397,7.41,162,26,12,368,159,2,40,18,Yes,Yes
398,5.94,100,79,7,284,95,0,50,12,Yes,Yes
399,9.71,134,37,0,27,120,1,49,16,Yes,Yes

In [12]:
data['Urban'].unique()

array(['Yes', 'No'], dtype=object)

In [6]:
#data['Urban'] = data['Urban'].strip()
data['Urban'] = data['Urban'].map({'Yes':1, 'No':0})
data

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,0,42,17,1,Yes
1,11.22,111,48,16,260,83,1,65,10,1,Yes
2,10.06,113,35,10,269,80,2,59,12,1,Yes
3,7.40,117,100,4,466,97,2,55,14,1,Yes
4,4.15,141,64,3,340,128,0,38,13,1,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,1,33,14,1,Yes
396,6.14,139,23,3,37,120,2,55,11,0,Yes
397,7.41,162,26,12,368,159,2,40,18,1,Yes
398,5.94,100,79,7,284,95,0,50,12,1,Yes
399,9.71,134,37,0,27,120,1,49,16,1,Yes

In [7]:
data['US'] = data['US'].map({'Yes':1, 'No':0})
data

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,0,42,17,1,1
1,11.22,111,48,16,260,83,1,65,10,1,1
2,10.06,113,35,10,269,80,2,59,12,1,1
3,7.40,117,100,4,466,97,2,55,14,1,1
4,4.15,141,64,3,340,128,0,38,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,1,33,14,1,1
396,6.14,139,23,3,37,120,2,55,11,0,1
397,7.41,162,26,12,368,159,2,40,18,1,1
398,5.94,100,79,7,284,95,0,50,12,1,1
399,9.71,134,37,0,27,120,1,49,16,1,1

In [9]:
X = data.drop(['US'], axis = 1)
Y = data['US']

In [2]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, Y_train, Y_test  = train_test_split(X,Y, test_size=0.3, random_state=42 )
X_train.shape, X_test.shape

((280, 10), (120, 10))

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
model = RandomForestClassifier()

In [16]:
model.fit(X_train, Y_train)

RandomForestClassifier()

In [17]:
model.feature_importances_

array([0.09044266, 0.04841535, 0.04890154, 0.56696278, 0.05957107,
       0.05564103, 0.01717858, 0.06525125, 0.03835818, 0.00927756])

In [18]:
pred = model.predict(X_test)
pred

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [21]:
accuracy = accuracy_score(Y_test, pred)*100
print("Accuracy Score:", accuracy)

Accuracy Score: 90.0

In [22]:
confusion_matrix(Y_test, pred)

array([[31,  5],
       [ 7, 77]])

### 2. Fraud_check

In [5]:
data1 = pd.read_csv("D:/Top mentor/Machine learning/Machine learning assinments/Random Forests - Assignment -5/10. Random Forests/Fraud_check.csv")
data1

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
...,...,...,...,...,...,...
595,YES,Divorced,76340,39492,7,YES
596,YES,Divorced,69967,55369,2,YES
597,NO,Divorced,47334,154058,0,YES
598,YES,Married,98592,180083,17,NO
599,NO,Divorced,96519,158137,16,NO

In [6]:
data1.isnull().sum()

Undergrad          0
Marital.Status     0
Taxable.Income     0
City.Population    0
Work.Experience    0
Urban              0
dtype: int64

In [7]:
data1.shape

(600, 6)

In [8]:
data1['Undergrad'].unique()

array(['NO', 'YES'], dtype=object)

In [9]:
data1['Undergrad'] = data1['Undergrad'].map({'NO':0, 'YES':1})
data1

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,0,Single,68833,50047,10,YES
1,1,Divorced,33700,134075,18,YES
2,0,Married,36925,160205,30,YES
3,1,Single,50190,193264,15,YES
4,0,Married,81002,27533,28,NO
...,...,...,...,...,...,...
595,1,Divorced,76340,39492,7,YES
596,1,Divorced,69967,55369,2,YES
597,0,Divorced,47334,154058,0,YES
598,1,Married,98592,180083,17,NO
599,0,Divorced,96519,158137,16,NO

In [10]:
data1['Urban'] = data1['Urban'].map({'NO':0, 'YES':1})
data1

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,0,Single,68833,50047,10,1
1,1,Divorced,33700,134075,18,1
2,0,Married,36925,160205,30,1
3,1,Single,50190,193264,15,1
4,0,Married,81002,27533,28,0
...,...,...,...,...,...,...
595,1,Divorced,76340,39492,7,1
596,1,Divorced,69967,55369,2,1
597,0,Divorced,47334,154058,0,1
598,1,Married,98592,180083,17,0
599,0,Divorced,96519,158137,16,0

In [11]:
data1['Marital.Status'].unique()

array(['Single', 'Divorced', 'Married'], dtype=object)

In [12]:
data1['Marital.Status'] = data1['Marital.Status'].map({'Single':1, 'Divorced':0, 'Married':2})
data1

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,0,1,68833,50047,10,1
1,1,0,33700,134075,18,1
2,0,2,36925,160205,30,1
3,1,1,50190,193264,15,1
4,0,2,81002,27533,28,0
...,...,...,...,...,...,...
595,1,0,76340,39492,7,1
596,1,0,69967,55369,2,1
597,0,0,47334,154058,0,1
598,1,2,98592,180083,17,0
599,0,0,96519,158137,16,0

In [13]:
X1 = data1.drop(['Urban'], axis=1)
Y1 = data1['Urban']

In [10]:
from sklearn.model_selection import train_test_split

In [20]:
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size=0.2, random_state=42)
X1_train.shape, X1_test.shape

((480, 5), (120, 5))

In [21]:
model1 = RandomForestClassifier()

In [22]:
model1.fit(X1_train, Y1_train)

RandomForestClassifier()

In [23]:
pred1 = model1.predict(X1_test)
pred1

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [24]:
accuracy1  = accuracy_score(Y1_test,pred1)
print("Accuracy score:", accuracy1)

Accuracy score: 0.5583333333333333

In [25]:
confusion_matrix(Y1_test, pred1)

array([[30, 26],
       [27, 37]])

In [28]:
print(classification_report(Y1_test, pred1))

              precision    recall  f1-score   support

           0       0.53      0.54      0.53        56
           1       0.59      0.58      0.58        64

    accuracy                           0.56       120
   macro avg       0.56      0.56      0.56       120
weighted avg       0.56      0.56      0.56       120